# Generated by Django 2.2 on 2019-09-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUp',
        ),
    ]
