# Generated by Django 2.2 on 2019-09-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_buyrecord_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytotal',
            name='num_book',
            field=models.IntegerField(default=1),
        ),
    ]
