# Generated by Django 2.2 on 2019-09-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('cat_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('book_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('book_available', models.BooleanField(default=False)),
                ('book_cat', models.ForeignKey(on_delete=None, to='book.BookCategory')),
            ],
        ),
    ]
