# Generated by Django 2.2 on 2019-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='cat_description',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
