# Generated by Django 2.2 on 2019-09-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='cat_description',
        ),
    ]
