# Generated by Django 2.2 on 2019-09-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190901_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='book_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
